blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions & Help
    url: https://github.com/SomeMedic/EverythingUI/discussions
    about: Please ask questions in the Discussions section
  - name: 💡 Feature Ideas
    url: https://github.com/SomeMedic/EverythingUI/discussions/categories/ideas
    about: Share your ideas for improving the library
  - name: 📚 Documentation
    url: https://github.com/SomeMedic/EverythingUI/wiki
    about: Check our documentation before creating an issue 